CREATE TABLE ORDERS (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    BOOK_ISBN VARCHAR(255) NOT NULL,
    BOOK_NAME VARCHAR(255) NOT NULL,
    BOOK_PRICE FLOAT8 NOT NULL,
    QUANTITY INT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL
)